worker_processes 1;
events {
    worker_connections 1024;
}
http {
    include mime.types;

    server {
        listen 80;
        root /app/web;
        index consumer-sip-ui-mf.js;
        location / {
          try_files $uri /consumer-sip-ui-mf.js;
        }
    }
}
