sonar.projectKey=rdx-sip-ui-mf
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=helm-chart-deployment/**/*, src/assets/**/*, src/mocks/**/* , src/coverage/**/* , **/__test__/**, **/__tests__/**,  src/theme/**/*, 
src/constants/**/*,  **/*.test.tsx, **/*/consumer-sip-ui-mf.tsx, **/*/index.tsx, **/*/main.tsx
sonar.language=ts
sonar.clover.reportPaths=coverage/clover.xml
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.tests=tests


sonar.host.url=https://sonarqube.kenvue.com/tutorials?id=rdx-sip-ui-mf
