export const ApiEndPoints = {
  getExperimentalAssessment: "/api/getProductExperimental?groupId=",
  experimental: `/api/experimental`,
  product_all_list: `/api/product`,
  product_my_product: `/api/product/myproduct`,
  product_detail_by_id: `/api/product/productDetails/`,
  product_detail_audit_report: `/api/product/product-details/auditreport`,
  assessment_delete: `/api/product/delete-assessment/`,
  assessment_add: `/api/product/add-assessment`,
  assessment_edit: `/api/product/edit-assessment`,
  assessment_detail_by_id: `/api/product/assessment/details/`,
  product_add: `/api/product/add-product`,
  product_edit: `/api/product/edit-product`,
  product_delete: `/api/product/delete/`,
  formula_codes: `/api/formula/formula-codes?initialLetters=`,
  formula_details: `/api/formula/formula-details/`,
  find_product: `/api/product-search/findProduct?initialLetters=`,
  find_product_details: `/api/product-search/findProduct/`,
  find_component: `/api/component-search/findComponent?initialLetters=`,
  find_component_details: `/api/component-search/findComponent/`,
  master_data: `/api/master-data`,
  add_member: `/api/product/add-member`,
  delete_member: `/api/product/delete-member/`,
  product_details: `/api/product/productDetails`,
  edit_member: "/api/product/edit-member/",
  add_packaging: "/api/product/assessment/add-packaging",
  add_update_packaging: "/api/product/assessment/add-update-packaging",
  edit_packaging: "/api/product/assessment/edit-packaging",
  delete_packaging: "/api/product/assessment/delete-packaging",
  add_update_formulation: "/api/product/assessment/add-update-formulation",
  get_rawMaterial: "/api/rm-search/findRawMaterial",
  get_useDose: "/api/segment/getUseDoseValue",
  calculate_result_by_id: "/api/calculate/result",
  calculate_formulation_result_by_id: "/api/calculate/formulation/result",
  assessment_detail_by_sip_id: `/api/product/assessmentDetails/`,
  product_detail_log_report: `/api/calculate/assessment/logs`,
  product_detail_log_input: `/api/calculate/assessment/input/logs`,
  get_change_log: `/api/changelog`,
  admin_version_history: `/api/admin/admin-version`,
  user_acknowledge_version: `/api/user`,
  version_based_product_result: `/api/admin/result`,
  version_based_assessment_history: `/api/admin/admin_version`,
};

export const ApiEndPointsURL = `${process.env.REACT_APP_API_BASE_URL}`;

export const ToastMessageNotificationTime = 2000;
